---
# Copyright 2016, Ian Cordasco
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: barbican_install_apt.yml
  static: no
  when:
    - ansible_pkg_mgr == 'apt'

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in barbican_developer_constraints %}
      {{ item }}
      {% endfor %}
  when: barbican_developer_mode | bool

- name: Install requires pip packages
  pip:
    name: "{{ barbican_requires_pip_packages | join(' ') }}"
    state: "{{ barbican_pip_package_state }}"
    extra_args: >-
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Get local venv checksum
  stat:
    path: "/var/cache/{{ barbican_venv_download_url | basename }}"
    get_md5: False
  when:
    - not barbican_developer_mode | bool
  register: local_venv_stat

- name: Get remote venv checksum
  uri:
    url: "{{ barbican_venv_download_url | replace('tgz', 'checksum') }}"
    return_content: True
  when:
    - not barbican_developer_mode | bool
  register: remote_venv_checksum

# TODO: When project moves to ansible 2 we can pass this a sha256sum which will:
#       a) allow us to remove force: yes
#       b) allow the module to calculate the checksum of dest file which would
#          result in file being downloaded only if provided and dest sha256sum
#          checksums differ
- name: Attempt venv download
  get_url:
    url: "{{ barbican_venv_download_url }}"
    dest: "/var/cache/{{ barbican_venv_download_url | basename }}"
    force: yes
  failed_when: false
  register: get_venv
  when:
    - not barbican_developer_mode | bool
    - (local_venv_stat.stat.exists == False or
        {{ local_venv_stat.stat.checksum is defined and local_venv_stat.stat.checksum != remote_venv_checksum.content | trim }})

- name: Set barbican get_venv fact
  set_fact:
    barbican_get_venv: "{{ get_venv }}"

- name: Remove existing venv
  file:
    path: "{{ barbican_bin | dirname }}"
    state: absent
  when:
    - barbican_get_venv | changed

- name: Create barbican venv dir
  file:
    path: "{{ barbican_bin | dirname }}"
    state: directory
  register: barbican_venv_dir
  when:
    - not barbican_developer_mode | bool

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ barbican_venv_download_url | basename }}"
    dest: "{{ barbican_bin | dirname }}"
    copy: "no"
  when:
    - not barbican_developer_mode | bool
    - barbican_get_venv | changed or barbican_venv_dir | changed
  notify: Restart barbican services

- name: Install pip packages
  pip:
    name: "{{ barbican_pip_packages | join(' ') }}"
    state: "{{ barbican_pip_package_state }}"
    virtualenv: "{{ barbican_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ barbican_developer_mode | ternary('--constraint /opt/developer-pip-constraints.txt', '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  when:
    - barbican_get_venv | failed or barbican_developer_mode | bool
  notify: Restart barbican services

- name: Update virtualenv path
  command: >
    virtualenv-tools --update-path=auto {{ barbican_bin | dirname }}
  when:
    - not barbican_developer_mode | bool
    - barbican_get_venv | success
